In [14]:
import torch
import numpy as np
import torchvision
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import matplotlib.pyplot as plt

In [15]:
import os
#change to your working directory
os.chdir('C:/Users/aliks/Desktop/Teaching/U of T Teaching/MMF Course/2021 Course')

In [16]:
#Basics of torch:

#We make two random tensors to inspect; these could represent, for example, time series data

#Dimension: batch size (3) x sequence length (28) * number of time series / features (4)
# e.g. 4 28-tick financial data time series in batches of 3

x1 = torch.rand(3, 28, 4)
x2 = torch.rand(3, 28, 4)

In [4]:
x1

tensor([[[9.3087e-01, 1.7315e-01, 2.8236e-01, 9.3444e-01],
         [2.5429e-01, 8.4608e-01, 4.4174e-01, 1.4539e-01],
         [3.0301e-01, 7.4598e-01, 9.3455e-01, 9.8392e-01],
         [2.9832e-04, 3.0653e-01, 4.5819e-01, 8.7662e-01],
         [6.1554e-01, 3.9989e-01, 8.4597e-01, 2.1477e-01],
         [4.6032e-01, 3.2748e-01, 4.7584e-02, 6.9092e-02],
         [1.4538e-01, 2.1016e-01, 3.9173e-01, 6.2923e-01],
         [3.6042e-01, 2.0448e-02, 8.0906e-01, 6.0462e-01],
         [2.0630e-02, 8.9155e-01, 5.1732e-01, 9.7579e-01],
         [2.1867e-01, 5.3230e-01, 9.2079e-01, 3.5374e-01],
         [2.0026e-01, 1.0386e-01, 5.3558e-01, 8.1438e-01],
         [9.9730e-01, 6.9433e-01, 1.1051e-01, 3.9944e-01],
         [8.8416e-01, 1.0234e-01, 5.1960e-02, 3.0556e-01],
         [8.5358e-01, 8.8885e-01, 9.8743e-01, 4.1355e-01],
         [1.4834e-01, 2.2713e-01, 8.0154e-01, 3.5502e-01],
         [6.9338e-01, 8.3720e-01, 7.4918e-01, 3.0379e-01],
         [4.8672e-01, 8.3447e-01, 8.7445e-01, 4.9836e-02

In [5]:
x1.shape

torch.Size([3, 28, 4])

In [6]:
(x1+x2)[1,:,:]

tensor([[0.7403, 1.0926, 1.6891, 0.4252],
        [1.5379, 0.6892, 1.3155, 1.3267],
        [1.6682, 1.2395, 1.8095, 1.5049],
        [1.1865, 1.2248, 1.2294, 1.8320],
        [1.2033, 1.0076, 0.9300, 1.0007],
        [1.9395, 1.0103, 1.0789, 1.4154],
        [0.5368, 0.4995, 1.2432, 1.5657],
        [0.7552, 1.2549, 0.7524, 0.5821],
        [0.7224, 0.5879, 0.7109, 0.4743],
        [0.9128, 0.3851, 1.1048, 1.2270],
        [0.4099, 0.6872, 0.3367, 1.5844],
        [0.6184, 1.7351, 1.4433, 0.2384],
        [0.7196, 0.6363, 0.9296, 1.1135],
        [0.0943, 0.7520, 0.7543, 0.3588],
        [1.0665, 0.6203, 0.4150, 0.6754],
        [0.7024, 1.5374, 0.9818, 1.7244],
        [1.0780, 0.7062, 0.5887, 1.1344],
        [1.2252, 0.8991, 1.5997, 0.3085],
        [1.7112, 1.1853, 0.7930, 1.0210],
        [1.3894, 1.0239, 0.5325, 1.1807],
        [1.0068, 1.5031, 1.3492, 1.2406],
        [1.7441, 0.8469, 1.8208, 1.5334],
        [0.7761, 1.5084, 1.1387, 1.4636],
        [1.2753, 1.4299, 0.9983, 1

In [7]:
(x1*x2).shape

torch.Size([3, 28, 4])

In [8]:
print(x1[0])
print(x2[0])

tensor([[9.3087e-01, 1.7315e-01, 2.8236e-01, 9.3444e-01],
        [2.5429e-01, 8.4608e-01, 4.4174e-01, 1.4539e-01],
        [3.0301e-01, 7.4598e-01, 9.3455e-01, 9.8392e-01],
        [2.9832e-04, 3.0653e-01, 4.5819e-01, 8.7662e-01],
        [6.1554e-01, 3.9989e-01, 8.4597e-01, 2.1477e-01],
        [4.6032e-01, 3.2748e-01, 4.7584e-02, 6.9092e-02],
        [1.4538e-01, 2.1016e-01, 3.9173e-01, 6.2923e-01],
        [3.6042e-01, 2.0448e-02, 8.0906e-01, 6.0462e-01],
        [2.0630e-02, 8.9155e-01, 5.1732e-01, 9.7579e-01],
        [2.1867e-01, 5.3230e-01, 9.2079e-01, 3.5374e-01],
        [2.0026e-01, 1.0386e-01, 5.3558e-01, 8.1438e-01],
        [9.9730e-01, 6.9433e-01, 1.1051e-01, 3.9944e-01],
        [8.8416e-01, 1.0234e-01, 5.1960e-02, 3.0556e-01],
        [8.5358e-01, 8.8885e-01, 9.8743e-01, 4.1355e-01],
        [1.4834e-01, 2.2713e-01, 8.0154e-01, 3.5502e-01],
        [6.9338e-01, 8.3720e-01, 7.4918e-01, 3.0379e-01],
        [4.8672e-01, 8.3447e-01, 8.7445e-01, 4.9836e-02],
        [2.135

In [9]:
(x1*x2)[0]

tensor([[3.0951e-01, 1.7142e-01, 7.0698e-02, 4.4846e-01],
        [5.9942e-02, 7.3000e-01, 1.0613e-01, 2.9244e-02],
        [9.0325e-02, 1.2790e-01, 7.8596e-01, 4.9655e-01],
        [1.8322e-04, 1.3746e-01, 2.3331e-01, 7.6966e-01],
        [6.0727e-01, 1.6784e-01, 3.6902e-01, 2.1066e-01],
        [3.6050e-01, 2.5973e-01, 4.2659e-02, 4.3844e-02],
        [6.6086e-02, 8.6714e-02, 1.9017e-01, 4.1354e-01],
        [3.7695e-02, 8.0110e-03, 6.2445e-01, 4.9805e-01],
        [1.7392e-02, 6.2511e-01, 4.0299e-01, 3.3808e-01],
        [1.2111e-01, 3.0087e-01, 3.2540e-01, 2.8954e-01],
        [7.5485e-03, 2.4254e-02, 1.0385e-01, 9.2448e-02],
        [7.8627e-01, 5.9022e-01, 8.0146e-02, 5.8349e-02],
        [6.2609e-01, 6.9364e-02, 2.7329e-02, 5.4543e-02],
        [1.7655e-01, 5.4987e-01, 6.7727e-01, 2.6422e-01],
        [1.1155e-01, 1.6761e-01, 4.4320e-01, 1.1913e-01],
        [2.9673e-01, 5.1630e-01, 3.8315e-01, 2.7767e-01],
        [3.2430e-01, 3.7537e-01, 1.6850e-01, 2.9621e-02],
        [1.602

In [23]:
#Tensor operation - slice a tensor; we can get 1 "feature" of our time series this way
x1[:,:,0:2]

tensor([[[0.2180, 0.4560],
         [0.2683, 0.7861],
         [0.1366, 0.6557],
         [0.5301, 0.0722],
         [0.0418, 0.5974],
         [0.2756, 0.6168],
         [0.0366, 0.2499],
         [0.6716, 0.2617],
         [0.5410, 0.9365],
         [0.4970, 0.0044],
         [0.7760, 0.7816],
         [0.6783, 0.9371],
         [0.6999, 0.6441],
         [0.0352, 0.3362],
         [0.6288, 0.1161],
         [0.3773, 0.8365],
         [0.4917, 0.2034],
         [0.2666, 0.4768],
         [0.0364, 0.3881],
         [0.8523, 0.4100],
         [0.9767, 0.0418],
         [0.6191, 0.9454],
         [0.7303, 0.0668],
         [0.2197, 0.7068],
         [0.3767, 0.8824],
         [0.8313, 0.4943],
         [0.7406, 0.6138],
         [0.3077, 0.0629]],

        [[0.6501, 0.7336],
         [0.5851, 0.4820],
         [0.4774, 0.1265],
         [0.4109, 0.1978],
         [0.0731, 0.4156],
         [0.7528, 0.3945],
         [0.3843, 0.9922],
         [0.6885, 0.5260],
         [0.1152, 0.8106],

In [11]:
#Example - vision

In [24]:
#Get sample MNIST data using pytorch library

batch_size_train=32
batch_size_test=64

train_loader = torch.utils.data.DataLoader(
  torchvision.datasets.MNIST('/files/', train=True, download=True,
                             transform=torchvision.transforms.Compose([
                               torchvision.transforms.ToTensor(),
                               torchvision.transforms.Normalize(
                                 (0.1307,), (0.3081,))
                             ])),
  batch_size=batch_size_train, shuffle=True)

test_loader = torch.utils.data.DataLoader(
  torchvision.datasets.MNIST('/files/', train=False, download=True,
                             transform=torchvision.transforms.Compose([
                               torchvision.transforms.ToTensor(),
                               torchvision.transforms.Normalize(
                                 (0.1307,), (0.3081,))
                             ])),
  batch_size=batch_size_test, shuffle=True)

In [25]:
#initialize networks parameters
MNIST_loss_func = F.nll_loss
evaluate_every = 500
non_decreasing_loss_to_stop = 3
learning_rate = 0.0001

In [26]:
#All this can be parametrized using a model config file, dictionary, or class

class MNIST_conv_net(nn.Module):
    def __init__(self):
        #This part of the class initializes the "shape" of our network, and creates the layers 
        #that have learned weights
        super(MNIST_conv_net, self).__init__()
        #input shape (Mnist images: batch size x 28 x 28 x 1)
        self.conv1 = nn.Conv2d(1, 64, kernel_size=5, stride=1)
        #shape after conv1: 24 x 24 x 64 (lose 4 pixes because no padding)
        #shape after max pool 1: 12 x 12 x 64 
        #   (kernel size reduces the images dimension by 5-1,
        #    max pool halves the image dimensions, channels is out_channels of our conv1 layer)
        self.conv2 = nn.Conv2d(64, 32, kernel_size=3, stride=1)
        #shape after conv2: 10 x 10 x 32
        #after max pool 2: 5 x 5 x 32
        self.drop1 = nn.Dropout()
        self.fc1 = nn.Linear(800, 252)
        self.drop2 = nn.Dropout()
        self.fc2 = nn.Linear(252, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2(x), 2))
        x = x.view(-1, 800)
        x = self.drop1(x)
        x = F.relu(self.fc1(x))
        x = self.drop2(x)
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)

In [27]:
def train(n_epochs, net):
    early_stopping_hit = False
    training_steps = []
    training_losses = []
    test_steps = []
    test_losses = []
    test_accuracies = []
    net.train()
    consecutive_losses = 0
    for e in range(n_epochs):
        for i, (inputs, target) in enumerate(train_loader):
            if torch.cuda.is_available:
                inputs = inputs.to(torch.cuda.current_device())
                target = target.to(torch.cuda.current_device())
            optimizer.zero_grad()
            output = net.forward(inputs)
            loss = MNIST_loss_func(output, target)
            loss.backward()
            training_steps.append(e*len(train_loader) + i)
            training_losses.append(loss.item())
            optimizer.step()
            if i % evaluate_every == 0:
                print('Average training loss for last {} steps is: \
                      {}'.format(evaluate_every, sum(training_losses[-evaluate_every:]) / evaluate_every
                ))
                test_loss, pct_acc = test(net)
                test_steps.append(e*len(train_loader) + i)
                test_losses.append(test_loss)
                test_accuracies.append(pct_acc)
                if test_loss == min(test_losses):
                    #Save the best model - optional, commented out
                    #torch.save(net.state_dict(), '/mnist_model.pth')
                    print('Improved on best loss')
                    consecutive_losses = 0
                else:
                    print('Did not improve on best loss for {} steps'.format(consecutive_losses + 1))
                    consecutive_losses += 1
                if len(test_losses) >= 3 and min(test_losses[-non_decreasing_loss_to_stop:]) > min(test_losses):
                    early_stopping_hit = True
                    print ('Stopping training...')
            if early_stopping_hit:
                break
        if early_stopping_hit:
            break
    return (training_steps, training_losses, test_steps, test_losses, test_accuracies)

In [28]:
def test(net):
    net.eval()
    test_loss = 0
    correct_count = 0
    with torch.no_grad():
        for inputs, target in test_loader:
            if torch.cuda.is_available:
                inputs = inputs.to(torch.cuda.current_device())
                target = target.to(torch.cuda.current_device())
            output = net.forward(inputs)
            test_loss += MNIST_loss_func(output, target, size_average=False).item()
            pred = output.data.max(1, keepdim=True)[1]
            correct_count += pred.eq(target.data.view_as(pred)).sum()
        test_loss = test_loss/len(test_loader.dataset)
        print('\nTest set: Avg. loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        test_loss, correct_count, len(test_loader.dataset),
        100. * correct_count / len(test_loader.dataset)))
        return(test_loss, correct_count / len(test_loader.dataset))

In [29]:
net = MNIST_conv_net()
if torch.cuda.is_available:
    device = torch.cuda.current_device()
    net.to(device)
    print('Using GPU: {}'.format(device))
optimizer = optim.Adam(net.parameters(), lr=learning_rate)
training_steps, training_losses, test_steps, test_losses, test_accuracies = train(10, net)

Using GPU: 0
Average training loss for last 500 steps is:                       0.004630856037139893


C:\Users\aliks\anaconda3\envs\mmf_env\lib\site-packages\torch\nn\_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))



Test set: Avg. loss: 2.3124, Accuracy: 847/10000 (8%)

Improved on best loss
Average training loss for last 500 steps is:                       0.6122326492145658

Test set: Avg. loss: 0.2105, Accuracy: 9365/10000 (94%)

Improved on best loss
Average training loss for last 500 steps is:                       0.15694427666440605

Test set: Avg. loss: 0.1172, Accuracy: 9654/10000 (97%)

Improved on best loss
Average training loss for last 500 steps is:                       0.1261236136201769

Test set: Avg. loss: 0.0969, Accuracy: 9700/10000 (97%)

Improved on best loss
Average training loss for last 500 steps is:                       0.09932576083205641

Test set: Avg. loss: 0.0725, Accuracy: 9784/10000 (98%)

Improved on best loss
Average training loss for last 500 steps is:                       0.08043095098854974

Test set: Avg. loss: 0.0742, Accuracy: 9769/10000 (98%)

Did not improve on best loss for 1 steps
Average training loss for last 500 steps is:                       0.0

In [ ]:
fig = plt.figure(figsize=(16, 12))
#plt.plot(training_steps, training_losses, color='teal')
plt.scatter(test_steps, test_losses, color='purple')
plt.legend(['Train loss (batch)', 'Test loss (average)'], loc='upper right')
plt.xlabel('Train steps')
plt.ylabel('Loss (negative log likelihood)')
fig

In [ ]:
#take a look at the images as a sanity check

dataiter = iter(train_loader)
images, labels = dataiter.next()
images = images.numpy() 
fig = plt.figure(figsize=(20, 4))
for idx in np.arange(10):
    ax = fig.add_subplot(2, 10/2, idx+1, xticks=[], yticks=[])
    plt.imshow(np.transpose(images[idx], (1, 2, 0)), cmap='gray')